config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#root'
  get '/commandline', to: 'pages#commandline' , as: 'commandline'
  get '/git_with_github_2', to: 'pages#github2' , as: 'github2'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def root
  end

  def commandline
  end

  def github2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # create text with an icon to the left for bootstrap menus and buttons
  def text_with_icon(text, icon_name)
    raw("#{icon(icon_name)} #{text}")
  end

  # generate a standard bootstrap glyphicon
  def icon(name)
    content_tag(:span, nil, class: "glyphicon glyphicon-#{name}")
  end

  # action name to use for the primary submit button on scaffold-created CRUD forms
  def btn_action_prefix
    case action_name
      when 'new', 'create'
        'Create'
      when 'edit', 'update'
        'Update'
      else
        nil
    end
  end

  # bootstrap icon name to use for the primary submit button on scaffold-created forms
  def action_icon_name
    case action_name
      when 'new', 'create'
        'plus'
      when 'edit', 'update'
        'edit'
      else
        nil
    end
  end

  def alert_class(alert_type)
    alert_type = {
      alert: 'danger',
      notice: 'info'
    }.with_indifferent_access.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Codexx Tutorials
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      nav.navbar.navbar-default.navbar-fixed-top role='navigation'
        .container
          .navbar-header
            button.button.navbar-toggle data-toggle='collapse' data-target='.navbar-collapse'
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand href='/' Codexx Tutorials
          .collapse.navbar-collapse
            ul.nav.navbar-nav.navbar-right
              / - if current_user
              /  li.dropdown
              /    a.dropdown-toggle href='#' data-toggle='dropdown'
              /      = current_user.email
              /      b.caret
              /    ul.dropdown-menu
              /      li= link_to text_with_icon('Sign Out', 'log-out'), sign_out_path
              / - else
              /  li= link_to text_with_icon('Sign In', 'log-in'), sign_in_path

      .container
        - flash.each do |name, msg|
          .alert.alert-dismissable class=alert_class(name)
            button.close type='button' data-dismiss='alert' aria-hidden='true' &times;
            = raw(msg)
        = yield

    footer
      .container
        p &copy; #{Date.current.year} All rights reserved.

app/views/pages/commandline.html.slim
.jumbotron
  h1 Command Line Tutorial
  br
  p Thursday, January 12 6:30pm
  p Anna Sherman

.jumbotron
  h1 Mac
  p cmd + space
  p terminal
  p enter

  h2 Optional
  p ssh codexx@ec2-184-72-116-165.compute-1.amazonaws.com
  p pw: codexx
.jumbotron
  h1 Windows
  p=link_to "Download PuTTy", "http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html"
  p Host: ec2-184-72-116-165.compute-1.amazonaws.com
  p user: codexx
  p pw: codexx

app/views/pages/github2.html.slim
.jumbotron
  h1 Git with Github 2.0 Tutorial
  br
  p Thursday, March 23 6:30pm
  p Anna Sherman

.jumbotron
  h1 General Links
  p
    =link_to "Set Up Git", "https://help.github.com/articles/set-up-git/"
  p
    =link_to "Download Git", "https://git-scm.com/downloads"
  p
    =link_to "Github", "https://github.com/"
  p
    =link_to "Spoon-Knife Repo", "https://github.com/octocat/Spoon-Knife"
  p
    =link_to "CodeXX Demo Repo", "https://github.com/cavewoman/codexx.github.io"
  p
    =link_to "Github Help", "https://help.github.com"


.jumbotron
  h1 Mac
  p cmd + space
  p terminal
  p enter

  h2 Optional
  p ssh codexx@ec2-184-72-116-165.compute-1.amazonaws.com
  p pw: codexx

  h2 Links
  p
    =link_to "Download Git", "http://git-scm.com/download/mac"

.jumbotron
  h1 Windows
  p=link_to "Download PuTTy", "http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html"
  p Host: ec2-184-72-116-165.compute-1.amazonaws.com
  p user: codexx
  p pw: codexx

  h2 Links
  p
    =link_to "Download Git", "http://git-scm.com/download/win"

app/views/pages/root.html.slim
.jumbotron
  h1 Tutorials
  p
    =link_to "Commandline", commandline_path
  p
    =link_to "Git With Github 2.0", github2_path